### ISSUE TITLE
App Server devuelve algo extraño

### ISSUE THREAD

**Issue by MartinCura** [martinvol/tallerII#13]
En un patrón que no pude identificar, el primer request por un usuario devolverá algo extraño, no parseable por JSON.

![image](https://cloud.githubusercontent.com/assets/14017665/18340398/175aac2c-757b-11e6-96ef-6f737729ee5c.png)

Al repetir el request, devuelve lo esperado.

**Comment by PaulaSaffioti** [comment]
Lo arreglé agregando el content-length al header
