### ISSUE TITLE
Servicio de recomendaciones

### ISSUE THREAD

**Issue by PaulaSaffioti** [martinvol/tallerII#27]
Permite
- [x] recomendar a alguien, así como des-rescomendarlo
- [x] ordenar a los usuarios por su popularidad == cantidad de recomendaciones
- [x] **consultar (listar) a los usuarios más populares del sistema**
- [ ] permitir ver la lista de "recomendadores" _(opcional)_

Este número de recomendaciones debe devolverse en búsquedas ( #33 ) y otros listados para poder ordenarlos o simplemente mostrarlo.
- [ ] Especificar en la API
- [ ] Testing

**Comment by MartinCura** [comment]
Si consideramos listar los más populares y eso, todavía faltan algunas cosas.

**Comment by MartinCura** [comment]
Se resuelve una vez que server tenga búsqueda que automáticamente ordene por recomendaciones.
