### ISSUE TITLE
Tokens

### ISSUE THREAD

**Issue by MartinCura** [martinvol/tallerII#29]
AppServer: Generar y guardar; recibir y revisar
Client: Recibir y guardar; enviar con cada request pertinente

Discutir posibilidades entre
- Pedir usuario y contraseña cada vez
- UyC se cargan en los _input_ pero el usuario debe iniciar sesión nuevamente
- _Tokens_ vencen pero con UyC guardados se pide uno nuevo automáticamente
- _Tokens_ que no vencen (o de muy larga duración) y solo se pierden cuando se cierra sesión (con un request DELETE token?)

Votaría entre las últimas 2 posibilidades ya que son las que mantienen al usuario "conectado".
@martinvol @PaulaSaffioti @milenaf30 
- [x] Especificar en la API
- [ ] Testing

**Comment by milenaf30** [comment]
Faltan los tests de la API con token supongo
