### ISSUE TITLE
Sacar fotos automáticas

### ISSUE THREAD

**Issue by martinvol** [martinvol/tallerII#55]

**Comment by martinvol** [comment]
Te creas un usuario y te tira una foto random

**Comment by MartinCura** [comment]
@PaulaSaffioti Cerrado desde que borraste las fotos de más, no?

**Comment by PaulaSaffioti** [comment]
Diria que si

**Comment by PaulaSaffioti** [comment]
Solo quedaron los usuarios 1, 2, 3, 4 y 5 asi que no  deberia volver a pasar
