### ISSUE TITLE
Si los mensajes llegan por firebase no se marca el visto

### ISSUE THREAD

**Issue by martinvol** [martinvol/tallerII#57]
Usuario A abre conversación con usuario B.
Usuario A recibe mensajes con la conversación abierta.
Usuario A va a la lista de conversaciones, ve que tiene mensajes sin abrir con B.

**Comment by martinvol** [comment]
También puede ser que si lo marque el visto, pero que cuando presiones el botón de back y veas la lista de conversaciones no se actualice y siga mostrando los no vistos.

**Comment by MartinCura** [comment]
Esto es algo que preví en el desarrollo y existe la posibilidad de que me haya olvidado de hacerlo. Ahora reviso.
